name: ci-test

on:
  push:
    # Skip the backend suite if all changes are docs
    paths-ignore:
      - "docs/**"
      - "**/*.md"
      - "**/*.qmd"
      - "*.md"
      - "codecov.yml"
      - ".envrc"
    branches:
      - main
      - master
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64]
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v4

      - name: Rust latest
        run: rustup update

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Poetry install
        run: poetry install --with="dev" --extras="duckdb"
        working-directory: ${{ github.workspace }}

      - name: maturin develop
        run: poetry run maturin develop --release
        working-directory: ${{ github.workspace }}

      - name: poetry pytest
        run: poetry run pytest --import-mode=importlib
        working-directory: ${{ github.workspace }}